version: '3'
services:
  analysis:
    build: .
    ports:
      - "5020:5020"
    command: ["gunicorn","--config=./gunicorn_dev.py", "soils:app"]
    container_name: soils-analysis
    user: 1000:1000
    volumes:
      - "./soils:/soils/soils"
