version: "3"
services:
    analysis:
        build:
            dockerfile: Dockerfile
            args:
                - INSTALL_DEV=true
        env_file:
            - dev.env
        ports:
            - "5020:5020"
        command: ["gunicorn", "--config=./gunicorn_dev.py", "soils.main:app"]
        container_name: soils-analysis
        user: 1000:1000
        volumes:
            - "./soils:/soils/soils"
            - "./test:/soils/test"
