version: '3'
services:
  analysis:
    build:
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    env_file:
      - .env
    ports:
      - "5020:5020"
    command: uvicorn soils.main:app --host 0.0.0.0 --port 5020 --reload
    container_name: soils-analysis
    user: 1000:1000
    volumes:
      - "./soils:/soils/soils"
      - "./test:/soils/test"
