service: soils

provider:
  name: aws
  runtime: python3.8

functions:
  analysis:
    handler: src/main.analysis
    events:
      - http:
          path: hello
          method: post
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    layer: true