version: '3'
services:
    localstack:
      image: localstack/localstack:0.10.6
      ports:
        - "4567-4597:4567-4597"
        - "8080:8080"
      environment:
        - SERVICES=
        - DEFAULT_REGION=us-east-1
        - AWS_XRAY_SDK_ENABLED=true
        - DEBUG=${DEBUG- }
        - DATA_DIR=${DATA_DIR- }
        - PORT_WEB_UI=${PORT_WEB_UI- }
        - LAMBDA_EXECUTOR=docker
        - LAMBDA_REMOTE_DOCKER=false
        - DOCKER_HOST=unix:///var/run/docker.sock
        - LAMBDA_DOCKER_NETWORK=localstack_default
      volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"